In [1]:
import numpy as np
import pandas as pd

C:\Users\e32cl\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\e32cl\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\e32cl\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
import scipy.io

In [3]:
from anomaly.base import AnomalyDetector

In [4]:
from river import metrics
from river.stream import iter_array

In [5]:
from models.xstream import xStream
from models.xstream_old import xStream_old

In [6]:
from pysad.evaluation import AUROCMetric

In [7]:
data = scipy.io.loadmat('C:/Users/e32cl/Documents/M2/P2 Data Stream/Projet/projet_v1/PySAD_to_River/data/arrhythmia.mat')
#data = scipy.io.loadmat('/Users/Sophie/Library/CloudStorage/OneDrive-Personnel/IP/Data Stream Processing/PySAD_to_River/data/arrhythmia.mat') 

In [8]:
X = data['X']
y = data['y']
y_flat = data['y'].flatten()

In [9]:
i = 0
for xi, yi in iter_array(X,y_flat):
    if i == 0:
        x0 = xi
    i+=1

### Arrays version

In [10]:
from models.xstream_old import xStream_old

In [11]:
model_old = xStream_old()
metric = AUROCMetric()

In [14]:
s = model_old.score_one(x0)
model_old = model_old.learn_one(x0)

In [15]:
s

array([-1.])

In [12]:
anom_scores = []
for xi, yi in iter_array(X,y_flat):
    anomaly_score = model_old.score_one(xi)
    model_old = model_old.learn_one(xi)
    metric.update(yi, anomaly_score)  # Update the AUROC metric.
    anom_scores.append(anomaly_score)
print(f"Area under ROC metric is {metric.get()}.")

deltamax [45.3537504  42.4698858  33.05618966 55.78069626 37.60282303 35.14331089
 36.54627204 22.13560932 31.05567098 40.77247601 33.49786262 36.41636823
 28.6394601  38.13975878 54.64620298 43.14538562 27.98994105 31.15093377
 37.89727167 29.02917153 32.01695918 23.21814108 26.41377482 36.39038747
 32.88298458 23.95426267 34.16470218 32.47595264 30.62265828 44.67825058
 36.23450289 36.97928474 29.58342779 28.28438969 29.18505611 22.10962856
 33.33331779 28.91658823 49.34612751 46.80001282 45.2584876  27.51362708
 46.05523097 35.42909927 31.83509384 44.62628906 29.85189567 27.46166555
 48.60134566 35.29919546 17.84012332 30.45811345 29.85189567 43.37055222
 20.2736547  38.00119472 35.95737477 22.24819262 33.59312541 21.68527611
 35.50704156 27.46166555 25.59105068 35.84479146 53.50304945 37.46425897
 31.9563374  35.51570181 29.32362017 33.80963176 36.07861832 41.94161031
 36.84938093 34.1993432  25.42650586 48.03842915 18.61954618 36.97062449
 32.57121544 41.88098853 35.385798   27.14

KeyboardInterrupt: 

In [13]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_flat,anom_scores)

0.6917098445595855

### Dict version

In [10]:
model = xStream()
metric = AUROCMetric()

In [11]:
#s1 = model.score_one(x0)
#model = model.learn_one(x0)

In [18]:
#s1

[-1.0]

In [11]:
anom_scores_dico = []
for xi, yi in iter_array(X,y_flat):
    anomaly_score = model.score_one(xi)
    model = model.learn_one(xi)
    metric.update(yi, anomaly_score)  # Update the AUROC metric.
    print(anomaly_score)
    anom_scores_dico.append(anomaly_score)
print(f"Area under ROC metric is {metric.get()}.")

[-1.0]
[-1.0]
[-1.02]
[-1.07]
[-1.01]
[-1.0]
[-1.06]
[-1.08]
[-1.06]
[-1.06]
[-1.06]
[-1.11]
[-1.08]
[-1.16]
[-1.1]
[-1.14]
[-1.15]
[-1.1]
[-1.211699250014423]
[-1.11]
[-1.16]
[-1.12]
[-1.18]
[-1.29]
deltamax {0: 45.35375039619101, 1: 42.469885801588845, 2: 33.05618966245203, 3: 55.78069625775568, 4: 37.60282303232032, 5: 35.143310885572504, 6: 36.54627203970334, 7: 22.135609320730246, 8: 31.055670979709955, 9: 40.77247601017137, 10: 33.49786261838205, 11: 36.41636822913565, 12: 28.63946010315139, 13: 38.13975878266667, 14: 54.6462029787981, 15: 43.145385616540736, 16: 27.989941050313064, 17: 31.150933774126255, 18: 37.89727166960704, 19: 29.02917153485439, 20: 32.016959177910714, 21: 23.218141075460803, 22: 26.413774815425377, 23: 36.390387467022116, 24: 32.88298458169514, 25: 23.95426266867757, 26: 34.1647021792961, 27: 32.47595264191638, 28: 30.622658277817756, 29: 44.67825058123918, 30: 36.2345028943409, 31: 36.97928474159554, 32: 29.583427793276435, 33: 28.284389687599766, 34: 29.

[-3.447136269265711]
[-2.1297727992349995]
[-3.6297976691464786]
[-3.472699950194153]
[-3.742924712352047]
[-3.6946550212859957]
[-3.610288984394164]
[-3.8093751972510863]
[-3.195338505288997]
[-2.938135148635935]
[-1.921680305731623]
[-3.5709425979526186]
[-3.243287250488988]
[-2.3007681559705087]
[-2.5552322854038034]
[-2.9958632427375442]
[-3.3043842224006776]
[-3.4563584384995045]
[-3.5696622504395368]
[-2.3633700973159746]
[-3.078396422296822]
[-3.298364808855892]
[-3.751568172553865]
[-2.831793600750112]
deltamax {0: 47.69201898640902, 1: 31.39342088718588, 2: 63.44502108124799, 3: 80.2892151848553, 4: 34.95278529673994, 5: 51.182101363660315, 6: 66.06041780067699, 7: 66.15568059509323, 8: 66.70127659947744, 9: 85.67589319639455, 10: 31.43672215737513, 11: 53.76285706693795, 12: 38.59875224667244, 13: 82.2204518352946, 14: 85.0696754137454, 15: 55.22643999933365, 16: 42.33132173698337, 17: 54.369074849587065, 18: 24.43057664075901, 19: 54.45567738996552, 20: 49.1123006486155, 21:

[-3.129433422519635]
[-2.788265526672398]
[-2.5491191856765467]
[-2.793939014199602]
[-3.2226929112520333]
[-3.4894182432012895]
[-3.11467690619241]
[-2.911690685180697]
[-2.75920722366098]
[-2.5762276421393127]
[-2.9702337461674717]
[-2.986919888984535]
[-2.807550984579117]
[-3.1227177367621253]
[-3.295668046678774]
[-3.0311137211212906]
[-2.710247333609157]
[-2.5590352364450646]
[-3.402250719468524]
[-2.916439835255427]
[-2.8088919849115452]
[-2.4230048385557232]
[-2.9614812849865557]
[-3.1725026481926433]
deltamax {0: 39.51673917468392, 1: 26.916069549620325, 2: 23.95426266867758, 3: 26.768845230977, 4: 42.71237291464852, 5: 33.930875320274325, 6: 48.29823676905815, 7: 22.326134909562832, 8: 33.91355481219862, 9: 29.704671349806237, 10: 23.67713453946656, 11: 20.100449621836837, 12: 21.278244170983655, 13: 29.999119987092953, 14: 53.580991732143204, 15: 36.7974194068008, 16: 32.666478230749036, 17: 31.69652977851047, 18: 31.679209270434768, 19: 34.38986878428005, 20: 40.555969659225

[-3.4129621799618395]
[-3.8747947108736485]
[-3.764293531927702]
[-3.6511098104514907]
[-3.66145495916187]
[-3.8932608096520642]
[-3.1262163806207353]
[-3.952435085532678]
[-3.893588470076112]
[-3.3601940842038713]
[-3.318338907999731]
[-4.075374161911456]
[-3.7626033361290716]
[-4.007868282180941]
[-3.667079436781537]
[-4.0675970350179345]
[-3.81355053326976]
[-3.8268113879556624]
[-2.8865789179284307]
[-4.096794518363184]
[-3.5889202741541544]
[-3.7331966356565442]
[-3.8774618673392665]
[-3.3100865466059246]
deltamax {0: 31.350119616996686, 1: 18.255815511775953, 2: 30.137684051698457, 3: 49.01703785419922, 4: 50.74042840773028, 5: 42.452565293513175, 6: 36.26914391049227, 7: 31.384760633148062, 8: 64.0772196260106, 9: 32.562555182294886, 10: 22.95833345432548, 11: 38.84989961376991, 12: 31.826433589078125, 13: 53.22592131659159, 14: 45.899346400575254, 15: 24.967512391105366, 16: 35.85345171667575, 17: 27.989941050313053, 18: 32.3720295934623, 19: 30.380171164758114, 20: 42.06285386

[-2.6252322854038037]
[-3.4775249897802416]
[-3.421126700547526]
[-2.9894632040947524]
[-3.297962752132457]
[-3.5156582261049976]
[-2.8273694033848606]
[-3.5431146627021253]
[-2.9772125385384047]
[-3.3295971370010142]
[-3.136564662047419]
[-3.3929914136507477]
[-2.859958424938956]
[-2.5163425985276913]
[-3.598569523831716]
[-3.4621598033007723]
[-2.299609861161593]
[-3.6406854788101994]
[-3.341122540418019]
[-3.1533332106567182]
[-2.8957670059628398]
[-3.388108217985756]
[-3.230890569624735]
[-3.314654803686449]
deltamax {0: 57.51274706532456, 1: 43.22332790288134, 2: 48.12503168830125, 3: 76.01970994419803, 4: 46.5315449453379, 5: 40.19223898963577, 6: 43.379212475562525, 7: 51.459229492871344, 8: 52.57640226375327, 9: 33.367958807814425, 10: 48.99971734612353, 11: 54.568260692457464, 12: 38.23502157708296, 13: 37.38631668137422, 14: 34.03479836872843, 15: 64.92592452171934, 16: 44.435763468179545, 17: 41.517257857425975, 18: 29.851895668449597, 19: 38.17439979881807, 20: 59.911637433

[-3.671619875601496]
[-3.2834485271925047]
[-3.581214068460734]
[-3.9387761366486354]
[-2.674055659016298]
[-3.168952724968423]
[-3.1152289316331125]
[-3.691330208993073]
[-3.646455837741078]
[-3.6885346586897585]
[-3.6212947142285596]
[-3.804799967166754]
[-3.5546158664551695]
[-2.8926919434736984]
[-3.126568383410024]
[-3.736416731645774]
[-3.454078877724565]
[-3.5744227719717956]
[-2.61023302143515]
[-3.4473191464586814]
[-2.9548128103120526]
[-3.4516076426963256]
[-3.430398032874862]
[-3.3882898477851615]
deltamax {0: 65.6533858608983, 1: 52.082767783596125, 2: 56.84590750441055, 3: 71.75020470354073, 4: 39.741905779667896, 5: 82.18581081914323, 6: 46.765371804359724, 7: 73.71608237013143, 8: 70.91882031590768, 9: 49.120960902653366, 10: 22.785128373568586, 11: 36.55493229374115, 12: 32.320068069235255, 13: 106.73763101643205, 14: 57.27025995226492, 15: 35.792829938410854, 16: 92.1884042328535, 17: 28.916588232362407, 18: 28.422953752205274, 19: 21.191641630605233, 20: 37.602823032

[-3.72580937006318]
[-3.743037342626447]
Area under ROC metric is 0.7093342753964516.


In [12]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_flat,anom_scores_dico)

0.7093342753964516

### Tests

In [2]:
d = {0:1.5,2:9,3:5}
d1 = {0:1,2:1,3:1}

In [19]:
Counter(d)

Counter({0: 1.5, 2: 9, 3: 5})

In [18]:
from collections import Counter
dict(Counter(d)+Counter(d1))

{0: 2.5, 2: 10, 3: 6}

In [17]:
tuple(d.values())

(1.5, 9, 5)

In [26]:
import math

In [27]:
my_dictionary = dict(map(lambda x: (x[0],math.log2(x[1]+1)), d.items()))

In [28]:
my_dictionary

{0: 1.3219280948873624, 2: 3.321928094887362, 3: 2.584962500721156}

In [29]:
min(list(my_dictionary.values()))

1.3219280948873624

In [15]:
d1 = {}
for i in range(20):
    d1[i] = np.random.randint(10)

In [16]:
import river
from river.utils import dict2numpy

In [17]:
i=0
for xi,yi in iter_array(X,y_flat):
    if i==0:
        x0 = xi
    i+=1

In [18]:
print(dict2numpy(d))
print(d1.values(),len(d1))
print(dict2numpy(d1),len(d1))

[1.5 9.  5. ]
dict_values([4, 8, 3, 7, 0, 4, 3, 5, 9, 1, 2, 2, 3, 7, 6, 2, 6, 6, 4, 5]) 20
[4 8 2 2 3 7 6 2 6 6 4 5 3 7 0 4 3 5 9 1] 20


In [19]:
np.asarray(list(d1.values()))

array([4, 8, 3, 7, 0, 4, 3, 5, 9, 1, 2, 2, 3, 7, 6, 2, 6, 6, 4, 5])

In [2]:
import numpy as np

In [14]:
liste = [1/2] * 100
liste_np = np.ones(100) * 0.5
print(len(liste))
print(liste_np.shape)

100
(100,)


In [42]:
deltamax = [1/2] * 100
deltamax_abs = [abs(x) for x in deltamax]
print(deltamax_abs)
print(np.abs(deltamax))
deltamax[deltamax_abs[0] <= 0.0001] = 1.0

[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [1]:
d = {(0,0): 1, (0,1): 2, (1,0): 3, (1,1): 4}

In [2]:
print(d)

{(0, 0): 1, (0, 1): 2, (1, 0): 3, (1, 1): 4}
